# Generated by Django 4.0.1 on 2022-01-09 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_drink_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kcal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('saturated_fat_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sugars_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('caffeing_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('drink_id', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('size_id', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2000)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drink')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='AllergyDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allergy')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drink')),
            ],
            options={
                'db_table': 'allergyDrinks',
            },
        ),
    ]
