# Generated by Django 4.0.1 on 2022-01-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allergy_nutrition_image_allergydrink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='allergy',
            new_name='name',
        ),
    ]
