# Generated by Django 4.0.1 on 2022-01-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_allergy_allergy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='caffeing_mg',
            new_name='caffein_mg',
        ),
    ]
