# Generated by Django 4.0.1 on 2022-01-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_caffeing_mg_nutrition_caffein_mg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='drink_id',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='size_id',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
    ]
